### ISSUE TITLE
question about udev package including pkgs.libinput.out

### ISSUE THREAD

**Issue by colemickens** [matthewbauer/nixiosk#5]
What does this do? Do you do it as part of your other non-kiosk systems?

```
services.udev.packages = [ pkgs.libinput.out ];
```

**Comment by matthewbauer** [comment]
It's taken from here:

https://github.com/B4dM4n/nixpkgs/blob/3155fbff0adcd8abf762a5689de4af1c7b93b974/nixos/modules/services/x11/hardware/libinput.nix#L208

Since we're not using x11, I had to manually include a few things like this. Looking at the source it looks like the rules only apply to wacom tablets, so you may be fine without it.

**Comment by colemickens** [comment]
Okay, I would assume something similar. I've not had an issue with regular mouse/keyboard/trackpad inputs with similar settings as you have here (wlroots-based things, no x11). Thanks for the link and explanation.
